version: "3"
services:
  api:
    image: simple-go
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8887:8888"
    networks:
      - host
networks:
  host: